language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-x86-android-29

before_script:
  - android list target
  - android list device
  - android list
  - android
  - which android
  - echo no | android create avd --force --name testAVD -t android-28 --package "system-images;android-28;google_apis_playstore;x86"
  - android list device
  - android list target
  - emulator -avd test -noaudio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build
  - ./gradlew test
  - ./gradlew connectedCheck
