language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-x86-android-29

before_install:
  # Install avdmanager and other tools
  - sdkmanager tools
  - which avdmanager
  - which android
  - sdkmanager "system-images;android-28;default;armeabi-v7a"
  - echo no | avdmanager create avd --force --name testAVD --package "system-images;android-28;default;armeabi-v7a"

before_script:
  - android list
  - android-wait-for-emulator
  # Disable animations
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build
  - ./gradlew test
  - ./gradlew connectedCheck
